#!/usr/bin/env bash

service="websdr-nb"

set -e
source_dir="$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)"
cd "$source_dir"

echo "Installing/updating ${service} .."

skel="${service}.service.skel"
temp="${service}.service"
sudo sed "s#{{directory}}#${source_dir}#g" < $skel > $temp
sudo mv -f $temp /etc/systemd/system/
sudo systemctl daemon-reload

echo "Enabling at boot.."

sudo systemctl enable "$service"

echo "Install Complete! (service not started)"
